// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'infrastructure/objectbox/entities/query_history.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 139463488354827916),
      name: 'QueryHistoryEntity',
      lastPropertyId: const IdUid(3, 6149508526505359811),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 1118066295274440942),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8020235618241731956),
            name: 'queryString',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 6149508526505359811),
            name: 'searchedAt',
            type: 12,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 139463488354827916),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    QueryHistoryEntity: EntityDefinition<QueryHistoryEntity>(
        model: _entities[0],
        toOneRelations: (QueryHistoryEntity object) => [],
        toManyRelations: (QueryHistoryEntity object) => {},
        getId: (QueryHistoryEntity object) => object.id,
        setId: (QueryHistoryEntity object, int id) {
          object.id = id;
        },
        objectToFB: (QueryHistoryEntity object, fb.Builder fbb) {
          final queryStringOffset = fbb.writeString(object.queryString);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, queryStringOffset);
          fbb.addInt64(2, object.searchedAt.microsecondsSinceEpoch * 1000);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = QueryHistoryEntity(
              queryString: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              searchedAt: DateTime.fromMicrosecondsSinceEpoch(
                  (const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0) /
                          1000)
                      .round()))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [QueryHistoryEntity] entity fields to define ObjectBox queries.
class QueryHistoryEntity_ {
  /// see [QueryHistoryEntity.id]
  static final id =
      QueryIntegerProperty<QueryHistoryEntity>(_entities[0].properties[0]);

  /// see [QueryHistoryEntity.queryString]
  static final queryString =
      QueryStringProperty<QueryHistoryEntity>(_entities[0].properties[1]);

  /// see [QueryHistoryEntity.searchedAt]
  static final searchedAt =
      QueryIntegerProperty<QueryHistoryEntity>(_entities[0].properties[2]);
}
