# Uncomment this line to define a global platform for your project
# platform :ios, '11.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end

  # Isar の iOS リリースビルドが失敗する件への暫定対応
  # Error (Xcode): Invalid value (Producer: 'LLVM14.0.0-rust-1.60.0-stable' Reader: 'LLVM APPLE_1_1300.0.29.30_0') for architecture arm64
  # Isar の iOS 向け動的ライブラリ（libisar.a）のリンクが arm64 で失敗する。
  # StackOverflowでは2.4.0にダウングレードすればよいと書かれているが、根本的には Bitcodeをオフにすればよいらしい。
  # https://stackoverflow.com/a/72186524
  # リポジトリ見に行ったらOFFになってたがまだ未リリースのようで、次のリリースでは修正されるはず。
  # https://github.com/isar/isar/blob/main/packages/isar_flutter_libs/ios/isar_flutter_libs.podspec#L19
  # 暫定的にPodfileのBicodeをオフにしておき、Isarライブラリがアップデートされたら元に戻す
  # https://stackoverflow.com/a/32685434
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end

end

